### DISCUSSION TITLE
the elements were left unbound

### DISCUSSION THREAD

**Discussion by Rasool-Ansari-Shaik** [apple/pkl#1070] [Q&A]
I have birds.pkl file where class definitions are available.
```
module com.example.pkl3.Birds

class BirdConfig {
  jsonSchema: JsonSchemaSetting
}

abstract class JsonSchemaSetting {
  type: *"inline"|"template"
}

class InlineJsonSchemaSetting extends JsonSchemaSetting {
  type = "inline"
  content: Any
}

class TemplateJsonSchemaSetting extends JsonSchemaSetting {
  type = "template"
  templateId: String
  config: Mapping<String, AlphaNumericString>
}

typealias AlphaNumericString = String(matches(Regex("[-_.a-zA-Z0-9]+")))

birdsConfig: Listing<BirdConfig>

output {
  value = birdsConfig
  renderer = new JsonRenderer {}
}
```

I have birds-data.pkl file with below data
```
amends "birds.pkl"

birdsConfig {
    new BirdConfig {
        jsonSchema = new TemplateJsonSchemaSetting {
            type = "template"
            templateId = "jsonschema/string_param"
            config {
                ["param_1"] = "cCode"
            }
        }
    }
}
```

I am using above pkl files in the springboot example [link](https://github.com/apple/pkl-spring/tree/main/samples/spring-boot-external-config)

when I run the application, I am getting below error
```
Binding to target [Bindable@54224125 type = java.util.List<com.example.pkl3.Birds$BirdConfig>, value = 'none', annotations = array<Annotation>[@org.pkl.config.java.mapper.Named("birdsConfig")], bindMethod = [null]] failed:

    Property: birdsconfig[0].jsonschema.config.param1
    Value: "cCode"
    Origin: "birdsConfig[0].jsonSchema.config.param_1" from property source "Config resource 'file [config/birds-data.pkl]' via location 'file:./config/birds-data.pkl'"
    Reason: The elements [birdsconfig[0].jsonschema.config.param1,birdsconfig[0].jsonschema.templateid,birdsconfig[0].jsonschema.type] were left unbound.
    Property: birdsconfig[0].jsonschema.templateid
    Value: "jsonschema/string_param"
    Origin: "birdsConfig[0].jsonSchema.templateId" from property source "Config resource 'file [config/birds-data.pkl]' via location 'file:./config/birds-data.pkl'"
    Reason: The elements [birdsconfig[0].jsonschema.config.param1,birdsconfig[0].jsonschema.templateid,birdsconfig[0].jsonschema.type] were left unbound.
    Property: birdsconfig[0].jsonschema.type
    Value: "template"
    Origin: "birdsConfig[0].jsonSchema.type" from property source "Config resource 'file [config/birds-data.pkl]' via location 'file:./config/birds-data.pkl'"
    Reason: The elements [birdsconfig[0].jsonschema.config.param1,birdsconfig[0].jsonschema.templateid,birdsconfig[0].jsonschema.type] were left unbound.

Action:

Update your application's configuration
```

I'm not getting the issue if I use the direct class instead of abstract inheritance class.

Please help me resolve this.
