### DISCUSSION TITLE
Output of Cloudformation YAML extensions

### DISCUSSION THREAD

**Discussion by patersoz** [apple/pkl#541] [Q&A] [answered]
I'm working with PKL and Cloudformation and I'm really happy with how easy PKL makes it to make slight customisations on a base solution. However, I'm trying to work out how to model Cloudformation intrinsic functions in a way that would allow the YAML renderer to work. I'm happy to write custom renderers - I'm just not sure of the best approach.

So how would I model in PKL something like:

```
Fn::Sub:
  - String
  - Var1Name: Var1Value
    Var2Name: Var2Value

Or:

!Sub
  - String
  - Var1Name: Var1Value
    Var2Name: Var2Value
```

Where for a PKL class like:

```
typealias ResourceReference = String(matches(Regex("!Ref .+$")))
typealias StringSubstitution = String(matches(Regex("!Sub .+$")))

typealias TagValueType = String(matches(Regex("^[a-zA-Z0-9_\\-\\.\\/=+@\\s]*$")))|ResourceReference|StringSubstitution

class Tag {
  Key:   String
  Value: TagValueType
}
```

Here I'm doing a simple version where "!Sub" is on a single line, but to create the multi-line example above would require another structure that I'm not quite sure how to construct.

**Comment by bioball** [comment, marked as answer]
This snippet is a YAML explicit tag, followed by a seq:
```yaml
!Sub
  - String
  - Var1Name: Var1Value
    Var2Name: Var2Value
```

Right now, our YAML renderer doesn't support directly rendering YAML explicit tags (although you can do whatever you want with a [RenderDirective](https://pkl-lang.org/package-docs/pkl/current/base/RenderDirective.html)).

So, the better option for Pkl is to render the something like the first snippet, because this is a regular map, where the key is "Fn::Sub", and the value is a seq.

The first snippet can be represented in Pkl like so:

```pkl
`Fn::Sub` {
  "String"
  new {
    ["Var1Name"] = "Var1Value"
    ["Var2Name"] = "Var2Value"
  }
}
```

By the way, a pattern you can use here is to define a class that uses a fixed property to define the output, and top-level properties as input parameters:

```pkl
class Sub {
  /// The value to be substituted
  hidden value: String

  /// Key-value pairs of things to be substituted by CloudFormation.
  hidden params: Mapping<String, Any>?

  fixed `Fn::Sub` = new Listing {
    value
    when (params != null) {
      params
    }
  }
}
```

Then usage like so:

```pkl
InstanceSecurityGroup {
  Type = "AWS::EC2::SecurityGroup"
  Properties {
    GroupDescription = new Sub { value = "SSH security group for ${AWS::StackName}" }
  }
}
```

This produces:

```yaml
InstanceSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription:
      Fn::Sub:
      - SSH security group for ${AWS::StackName}
```

Also: are you aware of [Rain](https://github.com/aws-cloudformation/rain)? It's a tool created by AWS for CloudFormation, and they already have support for Pkl, thanks to @ericzbeard. Might be worth trying that out!
