### DISCUSSION TITLE
Define class with variable number of properties

### DISCUSSION THREAD

**Discussion by ghyatzo** [apple/pkl#881] [Q&A] [answered]
Hello,

I was wondering if it was possible to create a type that must have a property, but otherwise its dynamic. 
 For example:
```pkl
class Example {
    description: String
    // Some sort of "Varargs" property definition.
}

example = new Example {
    description = "this is a test"
    
    additional_prop = "I am"
    another_prop = "flattening"
    last_prop = "a listing"
}
```
This question raised when I was trying to generate a pkl file that would emulate a `TOML` configuration file that has some tables of the form:
```toml
[[examples]]
description = "this is always here for all tables"
arbitrary_key1 = "blah  blah"
abritrary_key2 = "blih bloh"

[[examples]]
description = "this is always here for all tables"
another_arbitrary_key1 = "..."
another_arbitrary_key2 = ",,,"
another_arbitrary_key3 = ";;;"

# and so on
```

I could simply add a listing property in the class `Example`, but then it wouldn't be flat anymore in the rendered `TOML` file, but instead have an extra table
```
[[examples]]
description = ...

[examples.keys]
arbtrary_key1 = ...
...
```
