### ISSUE TITLE
How to reuse code in pkl

### ISSUE THREAD

**Issue by ruby109** [apple/pkl#312]
like I have a yml:
``` yaml
targetA :
    dependencies:
        - A
        - B
targetB:
    dependencies:
        - A
        - B
```

I only want to write the `dependencies` part once and use it in different target. How can I do it in pkl?
