### ISSUE TITLE
[Feature Request] Convert json/yaml to pkl object/class

### ISSUE THREAD

**Issue by bielikb** [apple/pkl#6]
**Problem statement:**
The adoption of jsons/yamls is pretty much spread across the community/orgs. `pkl` goal's to provide **configuration-as-code language with rich validation and tooling**. 
For the cases when `pkl` tool is the right fit this however entails a rather higher ramp up time for people converting the existing configurations -> pkl -> existing configuration format (json/yaml).

**Feature Request:**
A converter that would map the existing configurations into a templates + modules. 
Aware of the complexity of the existing json/yaml configurations, the first versions of the converter could support the simplest mappings && let the configuration authors to convert more complex definitions manually.

**Comment by jackkleeman** [comment]
Hey @bielikb! This should be fairly easy to do with a pkl file itself (very meta, I know). pkl files can read yaml files, and output  pcf, which is a static subset of pkl that you can then just copy straight into a new file (in fact, you can use pkl to write that file for you, thus making a script that does the full conversion)

Here's a simplified example:

`vars.yaml`
```yaml
varReference:
  - kind: HTTPRoute
    path: spec/rules/matches/headers/value
  - kind: HTTPRoute
    path: spec/hostnames
  - kind: HTTPRoute
    path: spec/rules/filters/urlRewrite/path/replaceFullPath
  - kind: HTTPRoute
    path: spec/rules/filters/requestRedirect/hostname
  - kind: HTTPRoute
    path: spec/rules/filters/requestHeaderModifier/set/value
  - kind: AuthenticationFilter
    path: spec/jwtProviders/audiences
```

`converter.pkl`
```pkl
import "pkl:yaml"

file = read("file:vars.yaml")
parsed = new yaml.Parser {}.parse(file)

output {
  value = parsed
}
```

```bash
$ pkl eval converter.pkl

varReference {
  new {
    kind = "HTTPRoute"
    path = "spec/rules/matches/headers/value"
  }
  new {
    kind = "HTTPRoute"
    path = "spec/hostnames"
  }
  new {
    kind = "HTTPRoute"
    path = "spec/rules/filters/urlRewrite/path/replaceFullPath"
  }
  new {
    kind = "HTTPRoute"
    path = "spec/rules/filters/requestRedirect/hostname"
  }
  new {
    kind = "HTTPRoute"
    path = "spec/rules/filters/requestHeaderModifier/set/value"
  }
  new {
    kind = "AuthenticationFilter"
    path = "spec/jwtProviders/audiences"
  }
}
```

This is essentially a [`Dynamic`](https://pkl-lang.org/package-docs/pkl/0.25.1/base/Dynamic) format, but with a bit of work you can copy the fields over to the equivalent typed objects (eg, there are typed for all the Kubernetes objects) using reflection. In time hopefully we can provide tools that do this for you :)
